WITH SOLIEU AS 
(
	SELECT *
	FROM
	(
	SELECT	DAUKY.debid							AS 'DAUKY_KHOANNO',
		DAUKY.sodudauky							AS 'DAUKY_SODU',
		DAUKY.crcontract_date						AS 'DAUKY_NGAYBATDAU',
		DAUKY.crcontract_end_date					AS 'DAUKY_NGAYTATTOAN',
		PHATSINH.debid							AS 'PS_KHOANNO',
		PHATSINH.crlimit						AS 'PS_SOTIEN',
		PHATSINH.crcontract_date					AS 'PS_NGAYBATDAU',
		PHATSINH.crcontract_end_date					AS 'PS_NGAYTATTOAN'
	FROM 
		(
			select	A.debid, B.sodudauky,A.crcontract_date,A.crcontract_end_date
			from	credit_contract a 
					inner join CREDIT_PLAN b on a.debid = b.debid 
			where	b.ngaydauky <= '2022-12-31' and b.ngaycuoiky >= '2022-12-31'
					and a.crcontract_end_date > '2022-12-31'
		) DAUKY
		FULL OUTER JOIN
		(
			select	debid, crlimit,crcontract_date,crcontract_end_date
			from	credit_contract
			where	YEAR( crcontract_date ) = 2023
		) PHATSINH ON DAUKY.debid = PHATSINH.debid 
	) X 
	LEFT JOIN
	(
		select		A.DEBID							AS 'THUHOI_KHOANNO', 
				SUM(gocphaitra)						AS 'THUHOI_TONGTHU',     
				A.crcontract_date					AS 'THUHOI_NGAYBATDAU',
				A.crcontract_end_date					AS 'THUHOI_NGAYTATTOAN'
		from		credit_contract a 
					inner join CREDIT_PLAN b on a.debid = b.debid  
		where		YEAR(dateadd(day,1,ngaycuoiky)) = 2023
		group by	a.debid ,A.crcontract_date, A.crcontract_end_date
	) Y ON ISNULL(X.DAUKY_KHOANNO,'') +  ISNULL(X.PS_KHOANNO,'') = Y.THUHOI_KHOANNO
	LEFT JOIN
	(
		select		A.debid							AS 'CUOIKY_KHOANNO', 
				B.sodudauky						AS 'CUOIKY_SODU',
				A.crcontract_date					AS 'CUOIKY_NGAYBATDAU',
				A.crcontract_end_date					AS 'CUOIKY_NGAYTATTOAN'
		from		credit_contract a 
					inner join CREDIT_PLAN b on a.debid = b.debid 
		where		ngaydauky <= '2023-12-31' and ngaycuoiky >= '2023-12-31'
					and crcontract_end_date > '2023-12-31'
	) Z ON ISNULL(X.DAUKY_KHOANNO,'') +  ISNULL(X.PS_KHOANNO,'') = Z.CUOIKY_KHOANNO
	LEFT JOIN
	(
		select		A.debid							AS 'TATTOAN_KHOANNO', 
				A.crlimit						AS 'TATTOAN_SOTIEN',
				A.crcontract_date					AS 'TATTOAN_NGAYBATDAU',
				A.crcontract_end_date					AS 'TATTOAN_NGAYTATTOAN'
		from		credit_contract a 
		where		YEAR(crcontract_end_date) = '2023'
	) W ON ISNULL(X.DAUKY_KHOANNO,'') +  ISNULL(X.PS_KHOANNO,'') = W.TATTOAN_KHOANNO
)
--DROP TABLE SOLIEU_FIANL
SELECT * 
INTO SOLIEU_FIANL
FROM SOLIEU


--- 1. SỐ HỢP ĐỒNG TÍN DỤNG---

-- ĐẦU KỲ VÀ CUỐI KỲ
SELECT
	COUNT(DAUKY_KHOANNO)	'Số khoản nợ đầu kỳ',
	COUNT(CUOIKY_KHOANNO)	'số cuối kỳ'
FROM	SOLIEU_FIANL

-- PHÁT SINH TĂNG 6T 
-- ĐẦU NĂM
SELECT		
	COUNT(PS_KHOANNO)	AS [PHÁT SINH TĂNG 6T ĐẦU NĂM]
FROM	SOLIEU_FIANL
WHERE PS_NGAYBATDAU BETWEEN '2023-01-01' AND '2023-06-30'
--CUỐI NĂM
SELECT		
	COUNT(PS_KHOANNO)	AS [PHÁT SINH TĂNG 6T CUỐI NĂM]
FROM	SOLIEU_FIANL
WHERE PS_NGAYBATDAU BETWEEN '2023-07-01' AND '2023-12-31'

-- PHÁT SINH GIẢM 6T 

-- ĐẦU NĂM

SELECT		
	COUNT(TATTOAN_KHOANNO)	AS [PHÁT SINH GIẢM 6T ĐẦU NĂM]
FROM	SOLIEU_FIANL
WHERE TATTOAN_NGAYTATTOAN BETWEEN '2023-01-01' AND '2023-06-30'

--CUỐI NĂM

SELECT		
	COUNT(TATTOAN_KHOANNO)	AS [PHÁT SINH GIẢM 6T CUỐI NĂM]
FROM	SOLIEU_FIANL
WHERE TATTOAN_NGAYTATTOAN BETWEEN '2023-07-01' AND '2023-12-31'

--- 2.DƯ NỢ TÍN DỤNG ---

-- ĐẦU KỲ VÀ CUỐI KỲ
SELECT
	sum(DAUKY_SODU)		'dư nợ gốc đầu kỳ',
	sum(CUOIKY_SODU)	'số cuối kỳ'
FROM	SOLIEU_FIANL ;

-- PHAT SINH TANG 6T 
-- DK

SELECT
	SUM(PS_SOTIEN)	AS [PHÁT SINH TĂNG 6T ĐẦU NĂM]
FROM SOLIEU_FIANL
WHERE PS_NGAYBATDAU BETWEEN '2023-01-01' AND '2023-06-30'

-- CK

SELECT
	SUM(PS_SOTIEN)	AS [PHÁT SINH TĂNG 6T CUỐI NĂM]
FROM SOLIEU_FIANL
WHERE PS_NGAYBATDAU BETWEEN '2023-07-01' AND '2023-12-31'

-- PHAT SINH GIAM 6T 
-- DK

SELECT
S	UM(THUHOI_TONGTHU)		AS [PHÁT SINH GIẢM 6T ĐẦU NĂM]
FROM 
(
	SELECT	DISTINCT
		THUHOI_KHOANNO
		,RANK () OVER (PARTITION BY THUHOI_KHOANNO ORDER BY ngaycuoiky desc) AS [RANK]
		,ngaycuoiky
		, THUHOI_TONGTHU
		FROM		SOLIEU_FIANL A
		LEFT JOIN CREDIT_PLAN B
		ON A.THUHOI_KHOANNO = B.debid
		WHERE dateadd(day,1,B.ngaycuoiky) BETWEEN '2023-01-01' AND '2023-12-31') X
WHERE ngaycuoiky BETWEEN '2023-01-01' AND '2023-06-30'
AND RANK = 1

-- CK

SELECT
	SUM(THUHOI_TONGTHU) AS [PHÁT SINH GIẢM 6T CUỐI NĂM]
FROM 
(
				SELECT		DISTINCT
		THUHOI_KHOANNO
		,RANK () OVER (PARTITION BY THUHOI_KHOANNO ORDER BY ngaycuoiky desc) AS [RANK]
		,ngaycuoiky
		, THUHOI_TONGTHU
				--	sum(A.THUHOI_TONGTHU)		'Số phát sinh giảm'
		FROM		SOLIEU_FIANL A
		LEFT JOIN CREDIT_PLAN B
		ON A.THUHOI_KHOANNO = B.debid
		WHERE dateadd(day,1,B.ngaycuoiky) BETWEEN '2023-01-01' AND '2023-12-31') X
WHERE ngaycuoiky BETWEEN '2023-07-01' AND '2023-12-31'
AND RANK = 1

-- 3. NUMBER OF CUSTOMERS

WITH SOLIEUKHACHHANG AS 
(
	SELECT *
	FROM
	(
	SELECT		DAUKY.custid			AS 'DAUKY_KH',
			DAUKY.tongtien			AS 'DAUKY_ST',
			DAUKY.ngaybatdau		AS 'DAUKY_NGAYBATDAU',
			DAUKY.ngaytattoan		AS 'DAUKY_NGAYTATTOAN',
			PHATSINH.custid			AS 'PHATSINH_KH',
			PHATSINH.tongtien		AS 'PHATSINH_ST',
			PHATSINH.ngaybatdau		AS 'PHATSINH_NGAYBATDAU',
			PHATSINH.ngaytattoan		AS 'PHATSINH_NGAYTATTOAN'
	FROM 
		(
			select	A.custid, 
				SUM(B.crlimit) 		AS 'tongtien',
				B.crcontract_date 	AS 'ngaybatdau',
				B.crcontract_end_date 	AS 'ngaytattoan'
			from	CUSTOMER  a 
					inner join credit_contract  b on a.custid  = b.custid  
			where	b.crcontract_end_date > '2022-12-31'
					AND B.crcontract_date <= '2022-12-31'
			group by a.custid, B.crcontract_date, B.crcontract_end_date 
		) DAUKY
		FULL OUTER JOIN
		(
			select	A.custid, 
				SUM(B.crlimit) 		AS 'tongtien',
				B.crcontract_date 	AS 'ngaybatdau',
				B.crcontract_end_date 	AS 'ngaytattoan'
			from	CUSTOMER  a 
					inner join credit_contract  b on a.custid  = b.custid  
			where	year(crcontract_date) = 2023
			group by a.custid,B.crcontract_date, B.crcontract_end_date  
		) PHATSINH ON DAUKY.custid = PHATSINH.custid
	) X 
	LEFT JOIN
	(
			select	A.custid		AS 'TATTOAN_KH', 
				SUM(B.crlimit)		AS 'TATTOAN_ST',
				B.crcontract_date 	AS 'TATTOAN_NGAYBATDAU',
				B.crcontract_end_date 	AS 'TATTOAN_NGAYTATTOAN'
			from	CUSTOMER  a 
					inner join credit_contract  b on a.custid  = b.custid  
			where	YEAR(crcontract_end_date) = '2023'
			group by a.custid,B.crcontract_date, B.crcontract_end_date 
	) Y ON ISNULL(X.DAUKY_KH,'') = Y.TATTOAN_KH OR ISNULL(X.PHATSINH_KH,'') = Y.TATTOAN_KH 
	LEFT JOIN
	(
			select	A.custid		AS 'CUOIKY_KH', 
				SUM(B.crlimit)		AS 'CUOIKY_ST',
				B.crcontract_date 	AS 'CUOIKY_NGAYBATDAU',
				B.crcontract_end_date 	AS 'CUOIKY_NGAYTATTOAN'
			from	CUSTOMER  a 
					inner join credit_contract  b on a.custid  = b.custid  
			where	b.crcontract_end_date > '2023-12-31'
					AND B.crcontract_date <= '2023-12-31'
			group by a.custid ,B.crcontract_date, B.crcontract_end_date 
	) Z ON ISNULL(X.DAUKY_KH,'') = Z.CUOIKY_KH or ISNULL(X.PHATSINH_KH,'')  = Z.CUOIKY_KH
)

SELECT * 
INTO SOLIEUKHACHHANG_FINAL
FROM SOLIEUKHACHHANG
--- KHÁCH HÀNG---
SELECT * FROM SOLIEUKHACHHANG_FINAL

-- DK

SELECT
	COUNT(DISTINCT(DAUKY_KH))	 AS [DK_SOLUONGKH]
FROM	SOLIEUKHACHHANG_FINAL

-- PHAT SINH MOI:

-- 6 THANG DK

SELECT
	COUNT(DISTINCT(PHATSINH_KH))  	AS [PSM6TDN_SOLUONGKH]
FROM
	(SELECT	
		PHATSINH_KH
	FROM SOLIEUKHACHHANG_FINAL
	WHERE PHATSINH_NGAYBATDAU BETWEEN '2023-01-01' AND '2023-06-30') PS_6TDN
	LEFT JOIN
	(SELECT	DAUKY_KH
	FROM SOLIEUKHACHHANG_FINAL) DK
	ON PS_6TDN.PHATSINH_KH = DK.DAUKY_KH
WHERE DK.DAUKY_KH IS NULL

-- 6 THANG CK

SELECT COUNT(DISTINCT(PS_6TCN.PHATSINH_KH))  AS [PSM6TCN_SOLUONGKH]
FROM
	(SELECT	
		PHATSINH_KH
	FROM SOLIEUKHACHHANG_FINAL
	WHERE PHATSINH_NGAYBATDAU BETWEEN '2023-07-01' AND '2023-12-31') PS_6TCN
	LEFT JOIN
	(SELECT	
		DAUKY_KH
	FROM SOLIEUKHACHHANG_FINAL) DK
	ON PS_6TCN.PHATSINH_KH = DK.DAUKY_KH
	LEFT JOIN
	(SELECT	
		PHATSINH_KH
	FROM SOLIEUKHACHHANG_FINAL
	WHERE PHATSINH_NGAYBATDAU BETWEEN '2023-01-01' AND '2023-06-30') PS_6TDN
	ON PS_6TCN.PHATSINH_KH = PS_6TDN.PHATSINH_KH
WHERE DK.DAUKY_KH IS NULL
AND PS_6TDN.PHATSINH_KH IS NULL

--- TAT TOAN

-- 6 THANG DK

SELECT COUNT(DISTINCT(TATTOAN_KH))  AS [PSG6TDN_SOLUONGKH]
FROM
	(SELECT	
		TATTOAN_KH
	FROM SOLIEUKHACHHANG_FINAL
	WHERE TATTOAN_NGAYTATTOAN BETWEEN '2023-01-01' AND '2023-06-30') TT_6TDN
	LEFT JOIN
	(SELECT 
		CUOIKY_KH
	FROM SOLIEUKHACHHANG_FINAL) CK
	ON TT_6TDN.TATTOAN_KH = CK.CUOIKY_KH
WHERE CK.CUOIKY_KH IS NULL

-- 6 THANG CK

SELECT COUNT(DISTINCT(TT_6TCN.TATTOAN_KH))  AS [PSG6TCN_SOLUONGKH]
FROM
	(SELECT	
		TATTOAN_KH
	FROM SOLIEUKHACHHANG_FINAL
	WHERE TATTOAN_NGAYTATTOAN BETWEEN '2023-07-01' AND '2023-12-31') TT_6TCN
	LEFT JOIN
	(SELECT	
		CUOIKY_KH
	FROM SOLIEUKHACHHANG_FINAL) CK
	ON TT_6TCN.TATTOAN_KH = CK.CUOIKY_KH
	LEFT JOIN
	(SELECT	
		TATTOAN_KH
	FROM SOLIEUKHACHHANG_FINAL
	WHERE TATTOAN_NGAYTATTOAN BETWEEN '2023-01-01' AND '2023-06-30') TT_6TDN
	ON TT_6TCN.TATTOAN_KH = TT_6TDN.TATTOAN_KH
WHERE CK.CUOIKY_KH IS NULL
AND TT_6TDN.TATTOAN_KH IS NULL

-- CK:

SELECT
	COUNT(DISTINCT(CUOIKY_KH))	AS [CK_SOLUONGKH]
FROM SOLIEUKHACHHANG_FINAL

--- 4. DISBURSEMENT AMOUNT

-- DK

SELECT 
	SUM(DAUKY_ST)	AS [DK_DUNO]
FROM
	(
	SELECT		DISTINCT
	DAUKY_KH
	,DAUKY_ST
	,DAUKY_NGAYBATDAU
	,DAUKY_NGAYTATTOAN-- CHECK LẠI XEM CÓ CẦN DÙNG DISTINCT HAY KO?
	FROM		SOLIEUKHACHHANG_FINAL
	) X

-- PHAT SINH MOI:

-- 6 THANG DK
SELECT
	SUM(PHATSINH_ST)	AS [PS6TDN_DUNO]
FROM(
	SELECT DISTINCT
	PHATSINH_KH
	,PHATSINH_ST
	,PHATSINH_NGAYBATDAU
	,PHATSINH_NGAYTATTOAN
	FROM SOLIEUKHACHHANG_FINAL
WHERE PHATSINH_NGAYBATDAU BETWEEN '2023-01-01' AND '2023-06-30') PS_6TDN


-- 6 THANG CK

SELECT
	SUM(PHATSINH_ST)	AS [PS6TCN_DUNO]
FROM(
	SELECT DISTINCT
	PHATSINH_KH
	,PHATSINH_ST
	,PHATSINH_NGAYBATDAU
	,PHATSINH_NGAYTATTOAN
	FROM SOLIEUKHACHHANG_FINAL
WHERE PHATSINH_NGAYBATDAU BETWEEN '2023-07-01' AND '2023-12-31') PS_6TCN

--- TAT TOAN

-- 6 THANG DK

SELECT 
	SUM(TATTOAN_ST)			AS [TT6TDN_DUNO]
FROM(
	SELECT DISTINCT
	TATTOAN_KH
	,TATTOAN_ST
	,TATTOAN_NGAYBATDAU
	,TATTOAN_NGAYTATTOAN
	FROM SOLIEUKHACHHANG_FINAL
WHERE TATTOAN_NGAYTATTOAN BETWEEN '2023-01-01' AND '2023-06-30') TT_6TDN


-- 6 THANG CK
SELECT 
	SUM(TATTOAN_ST)		 AS [TT6TCN_DUNO]
FROM(
	SELECT DISTINCT
	TATTOAN_KH
	,TATTOAN_ST
	,TATTOAN_NGAYBATDAU
	,TATTOAN_NGAYTATTOAN
	FROM SOLIEUKHACHHANG_FINAL
WHERE TATTOAN_NGAYTATTOAN BETWEEN '2023-07-01' AND '2023-12-31') TT_6TCN

-- CK:
SELECT 
	SUM(CUOIKY_ST)  AS [CK_DUNO]
FROM
	(
	SELECT DISTINCT
		CUOIKY_KH
		,CUOIKY_ST
		,CUOIKY_NGAYBATDAU
		,CUOIKY_NGAYTATTOAN
	FROM		SOLIEUKHACHHANG_FINAL
	) X
